### DISCUSSION TITLE
Add title under name

### DISCUSSION THREAD

**Discussion by yesidc** [rendercv/rendercv#137] [Q&A] [answered]
Hi,
how can I add a title under my name. Something like this:
```
cv:
   name: My Name
   title: Python developer
   location: ...
```
