### DISCUSSION TITLE
Adding a footer

### DISCUSSION THREAD

**Discussion by mattmaniak** [rendercv/rendercv#162] [Q&A] [answered]
Hi. Is there a way to add footer to a generated CV? In European countries it is often required to include a GDPR clause on the bottom of a doc.

**Comment by sinaatalay** [comment, marked as answer]
Hi. Yes, there is a way to do anything in RenderCV because you have complete control over the $\LaTeX$ code. You can update any template's `Preamble.j2.tex` file to set up a footer, as explained [here](https://docs.rendercv.com/user_guide/#overriding-built-in-themes).

Also, in `classic`, `sb2nov`, and `engineeringresumes` themes, there is a footer feature by default. Try using the code below in your YAML file:

```yaml
design:
  disable_page_numbering: false
  page_numbering_style: This is a footer with these placeholders: NAME, PAGE_NUMBER, TOTAL_PAGES, TODAY
```
