### DISCUSSION TITLE
How to add links for projects?

### DISCUSSION THREAD

**Discussion by andrefpoliveira** [rendercv/rendercv#22] [Q&A] [answered]
I think it would be great if we were able to add a link to some of the projects (App Store, Google Play, website,...).
This would allow a quick visualization of the project itself.

**Comment by sinaatalay** [comment, marked as answer]
Hello, this can already be achieved with Markdown links. RenderCV supports Markdown format, so you can use markdown in your entries.

Example:

```yaml
name: Some Project | [Google Play Store](https://example.com), [App Store]([Google Play Store](https://example.com))
location: Remote
date: 2021-09
highlights:
  - Developed a web application with **React** and **Django**.
  - Implemented a **RESTful API**
```

which will be rendered as:

![image](https://github.com/sinaatalay/rendercv/assets/79940989/e583bc7d-cbe7-453b-bc91-29c3a9882db6)

Or you can even do this in the `location` field, like shown below:

```yaml
name: Some Project
location: "[Google Play Store](https://example.com)"
date: 2021-09
highlights:
  - Developed a web application with **React** and **Django**.
  - Implemented a **RESTful API**
```

which will be rendered as:

![image](https://github.com/sinaatalay/rendercv/assets/79940989/b1354f6d-9dd8-4476-a1be-94a9e72ba26c)
