### DISCUSSION TITLE
Provide a setting parameter to keep all dates in ISO format (2020-01-01)

### DISCUSSION THREAD

**Discussion by Aithosa** [rendercv/rendercv#228] [Q&A] [answered]
What should I do if I want to keep dates in ISO format (2020-01-01). I don't want to convert them into human-friendly strings ("Jan 2020").

**Comment by sinaatalay** [comment, marked as answer]
This is possible. Please have a look at [`locale_catalog.date_style` field of the YAML file](https://docs.rendercv.com/user_guide/structure_of_the_yaml_input_file/#locale_catalog-field).

**Reply by Aithosa** [reply]
Like this? I tried and it works.
```yaml
locale_catalog:
  phone_number_format: national 
  date_style: "YEAR.MONTH_IN_TWO_DIGITS"  # It will render like: 2024.11(or you can replace "." to "-" to make it like 2024-11)
  month: month      # translation of the word "month"
  months: months    # translation of the word "months"
  year: year        # translation of the word "year"
  years: years      # translation of the word "years"
  present: present  # translation of the word "present"
  to: " - "            # translation of the word "to"  # use "-" to connect time period instad of 
```
