### DISCUSSION TITLE
Not sure how to actually use arbitrary keys in templates

### DISCUSSION THREAD

**Discussion by dfego** [rendercv/rendercv#375] [Q&A] [answered]
I've been reviewing the documentation and discussions here, and I've yet to find an actual _explanation_ as to how arbitrary keys are supposed to work. All I've found is [Using arbitrary keys](https://docs.rendercv.com/user_guide/structure_of_the_yaml_input_file/#using-arbitrary-keys), which says:

> By default, the an_arbitrary_key key will not affect the output as the default design options do not use it. However, you can use the an_arbitrary_key key in your own design options (see design.entry_types field).

So I look down at `design.entry_types` and there's no actual explanation of what to do. I think I've discovered the following through trial and error:

1. Lowercase keys are represented by all-caps in the templates
2. Using text in templates that is _not_ a key results in the literal text appearing
3. Using a key in _any_ entry makes it recognized as a key seemingly for any template

However, when I use my key (let's say `arbitrary`) in my entry_types, by putting the text `ARBITRARY`, it doesn't show up. It clearly is recognized as a key because of number 2 above not occurring.

Is there more documentation and examples around this that I haven't found, or does it not exist? I'm also looking for documentation on the `.j2.typ` files.

**Comment by sinaatalay** [comment]
Thank you, I agree that we need documentation for this.

Basically:

You can use the arbitrary keys in the `design.entry_types...` fields by writing them in all capital letters. Alternatively, you can just access them in the `*.j2.typ` files by using the syntax `<<entry.your_arbitrary_key>>`. All existing built-in templates serve as examples for this.

If you could prepare a minimal YAML example that shows an arbitrary key doesn't work in the `design.entry_types...` field, that would be great.

**Reply by dfego** [reply]
Attached an example. GitHub wouldn't let me name it `.yaml`, so I named it `.txt`.

[Example_CV.txt](https://github.com/user-attachments/files/19253469/Example_CV.txt)

I get the following. I added the comma and the extra position after arbitrary to make clear it's missing.

[Example_CV.pdf](https://github.com/user-attachments/files/19253476/Example_CV.pdf)

**Reply by eliluong** [reply]
I have the same problem, I made arbitrary key `test_random_key` and used it in `design.entry_types` as `TEST_RANDOM_KEY` but it does not appear.

```
cv:
  name: Eli Luong
  location: Address
  email: email@email.com
  phone: +1-410-523-1233
  website:
  sections:
    welcome_to_RenderCV!:
      - '[RenderCV](https://rendercv.com) is a Typst-based CV framework designed for academics and engineers, with Markdown syntax support.'
      - Each section title is arbitrary. Each section contains a list of entries, and there are 7 different entry types to choose from.
    professional_work_history:
      - entry_type: ExperienceEntry
        company: Some Company
        position: Low Level Position
        date:
        start_date: 2020-04
        end_date: present
        location: City, ST
        summary:
        highlights:
          - Developed deep learning models for the detection of gravitational waves in LIGO data
          - Published [3 peer-reviewed research papers](https://example.com) about the project and results
        test_random_key:
          - Stuff.
    experience:
      - company: Company C
        position: Summer Intern
        date:
        start_date: 2024-06
        end_date: 2024-09
        location: Livingston, LA, USA
        summary:
        highlights:
          - Developed deep learning models for the detection of gravitational waves in LIGO data
          - Published [3 peer-reviewed research papers](https://example.com) about the project and results
        test_random_key:
          - Stuff.
      - company: Company B
        position: Summer Intern
        date:
        start_date: 2023-06
        end_date: 2023-09
        location: Ankara, Türkiye
        summary:
        highlights:
          - Optimized the production line by 15% by implementing a new scheduling algorithm
design:
  entry_types:
    one_line_entry:
      template: '**LABEL:** DETAILS'
    education_entry:
      main_column_first_row_template: '**INSTITUTION**, AREA'
      degree_column_template: '**DEGREE**'
      degree_column_width: 1cm
      main_column_second_row_template: |-
        SUMMARY
        HIGHLIGHTS
      date_and_location_column_template: |-
        LOCATION
        DATE
    normal_entry:
      main_column_first_row_template: '**NAME**'
      main_column_second_row_template: |-
        SUMMARY
        HIGHLIGHTS
      date_and_location_column_template: |-
        LOCATION
        DATE
    experience_entry:
      main_column_first_row_template: '**COMPANY**'
      main_column_second_row_template: |-
        POSITION
        SUMMARY
        HIGHLIGHTS
        TEST_RANDOM_KEY
      date_and_location_column_template: |-
        LOCATION
        DATE
    publication_entry:
      main_column_first_row_template: '**TITLE**'
      main_column_second_row_template: |-
        AUTHORS
        URL (JOURNAL)
      main_column_second_row_without_journal_template: |-
        AUTHORS
        URL
      main_column_second_row_without_url_template: |-
        AUTHORS
        JOURNAL
      date_and_location_column_template: DATE
```
