### DISCUSSION TITLE
Allow users to create custom entries

### DISCUSSION THREAD

**Discussion by andrefpoliveira** [rendercv/rendercv#38] [Ideas]
I think it would be a good addition to allow users to create custom entries and use them in their CV

**Comment by sinaatalay** [comment]
This would be a good feature, but it's not very straightforward to implement, so I will skip it for a while and convert it into a discussion. But if you have any ideas for new built-in entry types, please let me know.

**Comment by arilwan** [comment]
Exactly, could be nice allow user add a section for example:
````
    personal:
      - nationality: MyCountry
      - date_of_birth: YYYY-MM-DD
      - etc: etc
````
