### DISCUSSION TITLE
Use a different font for parts of text

### DISCUSSION THREAD

**Discussion by HealthyPear** [rendercv/rendercv#385] [Q&A] [answered]
For example in a highlight of an ExperienceEntry, is it possible to use a different font for, say, a software name?

**Comment by sinaatalay** [comment, marked as answer]
Yes, it's possible as shown in the example below:

```yaml
cv:
  sections:
    experience:
      - company: Company
        position: '#text(font: "DejaVu Sans Mono")[your text]'
```

You can select any available font family from the full list provided [here](https://docs.rendercv.com/user_guide/structure_of_the_yaml_input_file/#design-field). Click the `+` button next to `design.text.font_family` in the example YAML to view all available fonts.

You can also surround the text with ` to display it in a monospace font.
