### DISCUSSION TITLE
How to properly put newlines in locations and dates?

### DISCUSSION THREAD

**Discussion by Prometheus3375** [rendercv/rendercv#401] [Q&A] [answered]
When RenderCV used LaTeX, I used `\\` to insert newlines in dates and locations.

![image](https://github.com/user-attachments/assets/a7a0e47c-ac6a-45f4-839a-5dd5d128a395)

But since LaTeX was changed to Typst, this no longer works. I found that `\n` achieves the desired result, but maybe there is a better way. Typst output contains `\` with newline, but it is invisible in pdf.

![image](https://github.com/user-attachments/assets/36486eb4-7c44-46f5-a61b-209f171962b7)

**Comment by sinaatalay** [comment, marked as answer]
With RenderCV v2.4, you can do:

```yaml
cv:
  sections:
    education:
      - institution: Princeton University
        area: Computer Science
        location: |-
          Princeton, NJ
          Remote
```

<img width="1225" height="153" alt="image" src="https://github.com/user-attachments/assets/d5bd074a-f131-4468-a83b-eab794600b97" />
