### DISCUSSION TITLE
Controlling the font size for specific fields

### DISCUSSION THREAD

**Discussion by dec-concannon** [rendercv/rendercv#431] [Q&A] [answered]
Wondering if it's possible to control the font size for a text field independently from what's defined in the design field. Here's what I was thinking might work, but it doesn't seem to:
```
cv:  
  sections:  
    TextEntry:  
      - '#text(font_size: 10pt)[This text is 10pt in size.]'  
    TextEntry:
      - This text is 8pt in size.

design:
  text:
    font_size: 8pt
```
