### ISSUE TITLE
Option to add relevant icon before sections

### ISSUE THREAD

**Issue by ferdavs** [rendercv/rendercv#106]
For example education section would start with `graduation-cap` icon, as I see tex file already uses package `fontawesome5`

So far tried to include graduation cap emoji in section  like:
```yaml
" education":
```
but TinyTex fails to render it.

Maybe it could be done in design section of the yaml file like:
```yaml

design:
  show_section_icons: true
  section_icons:
    - education: graduation-cap
    - projects: tasks
    - publications: file-alt
    - experience: briefcase
    - languages: language

```
