### ISSUE TITLE
Design Properties In Input File Cause Render Error

### ISSUE THREAD

**Issue by lolfert** [rendercv/rendercv#421]
When attempting to render a resume using the RenderCV CLI, I've found that there are several design properties that cause errors when used. These are `design.header.small_caps_for_name`, `design.header.use_urls_as_placeholders_for_connections`, `design.header.make_connections_links`, and `design.highlights.nested_bullet`. In my IDE, the YAML file passes validation against the [schema.json](https://github.com/rendercv/rendercv/blob/main/schema.json) without any issues. This suggests to me that the problem may lie within the rendering logic of RenderCV rather than the schema or YAML file.

**Steps to Reproduce:**
1. Add the mentioned properties under the `design` section in YAML input file.
2. Validate the YAML file against the schema.json in IDE (no errors are reported).
3. Attempt to render the resume using RenderCV CLI.
4. Observe the following rendering error.

```
rendercv render resumes/John_Doe_CV.yaml --watch
                                                                         
Welcome to RenderCV! Some useful links:                                  
┏━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃ Title             ┃                                              Link ┃
┡━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┩
│ RenderCV App      │                              https://rendercv.com │
│ Documentation     │                         https://docs.rendercv.com │
│ Source code       │             https://github.com/rendercv/rendercv/ │
│ Bug reports       │      https://github.com/rendercv/rendercv/issues/ │
│ Feature requests  │      https://github.com/rendercv/rendercv/issues/ │
│ Discussions       │ https://github.com/rendercv/rendercv/discussions/ │
│ RenderCV Pipeline │    https://github.com/rendercv/rendercv-pipeline/ │
└───────────────────┴───────────────────────────────────────────────────┘
╭──────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ 12 ms Validating the input file has started.                                                                 │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
14 ms ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ (0 out of 6 steps finished)
                                                                                                                
There are some errors in the data model!                                                                        
                                                                                                                
┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃ Location                                               ┃ Input Value ┃ Error Message                         ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┩
│ design.header.small_caps_for_name                      │ True        │ This field is unknown for this        │
│                                                        │             │ object! Please remove it.             │
├────────────────────────────────────────────────────────┼─────────────┼───────────────────────────────────────┤
│ design.header.use_urls_as_placeholders_for_connections │ True        │ This field is unknown for this        │
│                                                        │             │ object! Please remove it.             │
├────────────────────────────────────────────────────────┼─────────────┼───────────────────────────────────────┤
│ design.header.make_connections_links                   │ True        │ This field is unknown for this        │
│                                                        │             │ object! Please remove it.             │
├────────────────────────────────────────────────────────┼─────────────┼───────────────────────────────────────┤
│ design.highlights.nested_bullet                        │ •           │ This field is unknown for this        │
│                                                        │             │ object! Please remove it.             │
└────────────────────────────────────────────────────────┴─────────────┴───────────────────────────────────────┘
```

**Expected Behavior:**
The resume should render successfully, as the properties are valid according to the schema.

**Actual Behavior:**
The rendering process fails, citing that the properties are unrecognized.

**Environment:**
- RenderCV version: 2.2
- Operating System: Linux
- Date: May 2, 2025

**Content Of Input File** 
```
cv:
  name: "John Doe"
  website:
  location: Location
  email: john.doe@example.com
  phone: tel:+1-609-999-9995
  social_networks:
    - network: LinkedIn
      username: john.doe
    - network: GitHub
      username: john.doe
  sections:
    welcome_to_RenderCV!:
      - "[RenderCV](https://rendercv.com) is a Typst-based CV
        framework designed for academics and engineers, with Markdown
        syntax support."
      - Each section title is arbitrary. Each section contains
        a list of entries, and there are 7 different entry types
        to choose from.
    education:
      - institution: Stanford University
        area: Computer Science
        degree: PhD
        location: Stanford, CA, USA
        start_date: 2023-09
        end_date: present
        highlights:
          - Working on the optimization of autonomous vehicles
            in urban environments
design:
  theme: "engineeringresumes"
  page:
    size: "us-letter"
    top_margin: "0.4in"
    bottom_margin: "0.4in"
    left_margin: "0.4in"
    right_margin: "0.4in"
    show_page_numbering: false
  colors:
    text: "rgb(0, 0, 0)"
    name: "rgb(0, 0, 0)"
    connections: "rgb(0, 0, 0)"
    section_titles: "rgb(0, 0, 0)"
    links: "rgb(0, 0, 0)"
    last_updated_date_and_page_numbering: "rgb(128, 128, 128)"
  text:
    font_family: "EB Garamond"
    font_size: "10pt"
    leading: "0.6em"
    alignment: "justified"
    date_and_location_column_alignment: "right"
  links:
    underline: true
    use_external_link_icon: false
  header:
    name_font_family: "EB Garamond"
    name_font_size: "1.85em"
    small_caps_for_name: true
    name_bold: false
    photo_width: "0em"
    vertical_space_between_name_and_connections: "12pt"
    vertical_space_between_connections_and_first_section: "12pt"
    horizontal_space_between_connections: "1.25em"
    connections_font_family: "EB Garamond"
    separator_between_connections: "|"
    use_icons_for_connections: false
    use_urls_as_placeholders_for_connections: true
    make_connections_links: true
    alignment: "center"
  section_titles:
    type: "with-full-line"
    font_family: "EB Garamond"
    font_size: "1.2em"
    bold: true
    small_caps: true
    line_thickness: "0.5pt"
    vertical_space_above: "1.5em"
    vertical_space_below: "1em"
  entries:
    date_and_location_width: "4.15cm"
    left_and_right_margin: "0cm"
    horizontal_space_between_columns: "0.1cm"
    vertical_space_between_entries: "1.5em"
    allow_page_break_in_sections: true
    allow_page_break_in_entries: false
    short_second_row: false
  highlights:
    bullet: "•"
    nested_bullet: "•"
    top_margin: "1.25em"
    left_margin: "0.25cm"
    vertical_space_between_highlights: "1em"
    horizontal_space_between_bullet_and_highlight: "0.75em"
    summary_left_margin: "0.00em"
  entry_types:
    one_line_entry:
      template: "**LABEL:** DETAILS"
    education_entry:
      main_column_first_row_template: "**INSTITUTION**, DEGREE -- AREA -- LOCATION"
      degree_column_template:
      degree_column_width: "1cm"
      main_column_second_row_template: |-
        SUMMARY
        HIGHLIGHTS
      date_and_location_column_template: "DATE"
    normal_entry:
      main_column_first_row_template: "**NAME** -- **LOCATION**"
      main_column_second_row_template: |-
        SUMMARY
        HIGHLIGHTS
      date_and_location_column_template: "DATE"
    experience_entry:
      main_column_first_row_template: "**POSITION**, COMPANY -- LOCATION"
      main_column_second_row_template: |-
        SUMMARY
        HIGHLIGHTS
      date_and_location_column_template: "DATE"
    publication_entry:
      main_column_first_row_template: "**TITLE**"
      main_column_second_row_template: |-
        AUTHORS
        URL (JOURNAL)
      main_column_second_row_without_journal_template: |-
        AUTHORS
        URL
      main_column_second_row_without_url_template: |-
        AUTHORS
        JOURNAL
      date_and_location_column_template: "DATE"
locale:
  language: "en"
  phone_number_format: "national"
  page_numbering_template: "NAME - Page PAGE_NUMBER of TOTAL_PAGES"
  last_updated_date_template: "Last updated in TODAY"
  date_template: "MONTH_ABBREVIATION YEAR"
  month: "month"
  months: "months"
  year: "year"
  years: "years"
  present: "Present"
  to: "–"
  abbreviations_for_months:
    - "Jan"
    - "Feb"
    - "Mar"
    - "Apr"
    - "May"
    - "June"
    - "July"
    - "Aug"
    - "Sept"
    - "Oct"
    - "Nov"
    - "Dec"
  full_names_of_months:
    - "January"
    - "February"
    - "March"
    - "April"
    - "May"
    - "June"
    - "July"
    - "August"
    - "September"
    - "October"
    - "November"
    - "December"
```
```
